from distutils.core import setup

setup(name='Thoughts_API',
      version='0.0',
      description='Funness!',
      author='Norton Pengra',
      author_email='norton.pengra@outlook.com',
      packages=['Django',
                'Markdown',
                'Pillow',
                'Pygments',
                'backports.shutil-get-terminal-size',
                'decorator',
                'django-filter',
                'django-registration',
                'djangorestframework',
                'factory-boy',
                'fake-factory',
                'ipython',
                'ipython-genutils',
                'pexpect',
                'pickleshare',
                'ptyprocess',
                'python-dateutil',
                'simplegeneric',
                'six',
                'sorl-thumbnail',
                'traitlets',
            ],
    )
