---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=imgur.conf.j2 dest=/etc/init/imgur.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=imgur state=restarted
